name: "projet_mon_app"

services:
  api:
    build:
      context: "."
    ports:
      - "3000:3000"
    networks:
      - back
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=todolist_db
    ports:
      - 5000:5000
    networks:
      - back
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  back: