name: Pipeline Test Express

# Le robot se réveille dès qu'il y a un push ou une PR sur main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verifier-node:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: 2. Installer Node.js sur le robot
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Installer les dépendances (express, etc.)
        run: npm install

      - name: 4. Message de succès
        run: echo "Le robot a réussi à installer l'application sans erreur !"